### ISSUE TITLE
Executor does not work on melodic because tf2 cannot be imported

### ISSUE THREAD

**Issue by HiroIshida** [HiroIshida/mohou_ros#32]
### desction 
I am trying to add a rostest for executor https://github.com/HiroIshida/mohou_ros/pull/31
And I found that melodic-test fails, though the noetic-test passed. The CI log reveals the causes that it causes by the import error of tf2 when importing scikitrobot.interface.ros.pr2 module. 

As I remember correctly, this bug showed up when you @Kanazawanaoaki  tried to run the executor on melodic when you tried mohou package at the first time. So, I want you to fix this error.  

```
Traceback (most recent call last):
  File "/home/runner/work/catkin_ws/src/mohou_ros/rostest/run_data_collection.py", line 17, in <module>
    from mohou_ros_utils.rosbag import bag_to_seqs
  File "/home/runner/.local/lib/python3.6/site-packages/mohou_ros_utils/rosbag.py", line 6, in <module>
    from mohou_ros_utils.interpolator import (
  File "/home/runner/.local/lib/python3.6/site-packages/mohou_ros_utils/interpolator.py", line 12, in <module>
    from mohou_ros_utils.conversion import imgmsg_to_numpy, numpy_to_imgmsg
  File "/home/runner/.local/lib/python3.6/site-packages/mohou_ros_utils/conversion.py", line 23, in <module>
    from mohou_ros_utils.utils import deprecated
  File "/home/runner/.local/lib/python3.6/site-packages/mohou_ros_utils/utils.py", line 8, in <module>
    from skrobot.coordinates import Coordinates
  File "/home/runner/.local/lib/python3.6/site-packages/skrobot/__init__.py", line 15, in <module>
    from skrobot import interfaces
  File "/home/runner/.local/lib/python3.6/site-packages/skrobot/interfaces/__init__.py", line 6, in <module>
    from .ros import *
  File "/home/runner/.local/lib/python3.6/site-packages/skrobot/interfaces/ros/__init__.py", line 8, in <module>
    from .pr2 import PR2ROSRobotInterface
  File "/home/runner/.local/lib/python3.6/site-packages/skrobot/interfaces/ros/pr2.py", line 10, in <module>
    from .move_base import ROSRobotMoveBaseInterface
  File "/home/runner/.local/lib/python3.6/site-packages/skrobot/interfaces/ros/move_base.py", line 22, in <module>
    from .transform_listener import TransformListener
  File "/home/runner/.local/lib/python3.6/site-packages/skrobot/interfaces/ros/transform_listener.py", line 3, in <module>
    import tf
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/__init__.py", line 30, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_ros/__init__.py", line 38, in <module>
    from tf2_py import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_py/__init__.py", line 38, in <module>
    from ._tf2 import *
ImportError: dynamic module does not define module export function (PyInit__tf2)
```

### NOTE
When you look the log of the CI, you may think it is strange that the error caused in the data-collection phase, which worked fine so far. The following is the reason for that.

When one use the scikit-robot via pip installation, this error does not show up in the data-collection phase, but only in the execution phase, because only in the execution phase, pr2 module is imported from scikit-robot. However, in order to show the error expressively, I am using the following modified scikit-robot pacakge in the github workflow. This is the reason why, the import error appears in the data-collection test.

modified scikit-robot package 
https://github.com/HiroIshida/scikit-robot/commit/3ffb23c2447727b03266bb2dcacd286771770efa

modification in the workflow:
https://github.com/HiroIshida/mohou_ros/pull/31/commits/68f0e9f7247948d25167ba9e9dc7b30580f43f00

**Comment by Kanazawanaoaki** [comment]
This [ROS Answers](https://answers.ros.org/question/326226/importerror-dynamic-module-does-not-define-module-export-function-pyinit__tf2/  ) may be helpful, so I will modify it based on this.
